language: go
sudo: required
services:
  - docker
before_install:
  - sudo apt-get -qqy update
  - sudo mkdir -p misc/test/data/prouser/stor
  - sudo mkdir -p misc/test/data/vsuser/stor
  - sudo chmod -R 777 misc/test/data

script:
  - GO="GO111MODULE=on go" make ci

go:
  - 1.15
cache:
  directories:
    - misc/test/data
    - /go/src/github.com
